# Generated by Django 3.2.9 on 2022-01-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='image_url',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
